// Code generated by goyacc -o cmd/parser.go -v cmd/parser.output cmd/grammar.y. DO NOT EDIT.

//line cmd/grammar.y:1

package main

import __yyfmt__ "fmt"

//line cmd/grammar.y:3

import (
	"fmt"
)

//line cmd/grammar.y:10
type yySymType struct {
	yys    int
	String string
	Ast    ast
}

const NUMBER = 57346
const IDENTIFIER = 57347
const SEPARATOR = 57348
const ASSIGN = 57349
const LET = 57350
const IF = 57351
const THEN = 57352
const LE = 57353
const GE = 57354
const EQ = 57355
const NE = 57356
const OR = 57357
const AND = 57358
const ELSE = 57359
const NO_ELSE = 57360
const UMINUS = 57361

var yyToknames = [...]string{
	"$end",
	"error",
	"$unk",
	"NUMBER",
	"IDENTIFIER",
	"SEPARATOR",
	"ASSIGN",
	"LET",
	"IF",
	"THEN",
	"LE",
	"GE",
	"EQ",
	"NE",
	"OR",
	"AND",
	"ELSE",
	"NO_ELSE",
	"'+'",
	"'-'",
	"'*'",
	"'/'",
	"UMINUS",
	"'('",
	"')'",
	"'{'",
	"'}'",
}
var yyStatenames = [...]string{}

const yyEofCode = 1
const yyErrCode = 2
const yyInitialStackSize = 16

//line cmd/grammar.y:73

//line yacctab:1
var yyExca = [...]int{
	-1, 1,
	1, -1,
	-2, 0,
}

const yyPrivate = 57344

const yyLast = 114

var yyAct = [...]int{

	3, 44, 51, 46, 49, 43, 27, 15, 16, 24,
	25, 6, 7, 48, 28, 29, 30, 31, 32, 33,
	34, 35, 36, 37, 39, 23, 26, 9, 40, 1,
	45, 8, 2, 5, 17, 18, 19, 20, 21, 22,
	41, 4, 13, 14, 15, 16, 0, 47, 42, 0,
	0, 50, 17, 18, 19, 20, 21, 22, 0, 0,
	13, 14, 15, 16, 12, 0, 38, 0, 0, 17,
	18, 19, 20, 21, 22, 0, 0, 13, 14, 15,
	16, 17, 18, 19, 20, 21, 22, 0, 0, 13,
	14, 15, 16, 6, 7, 0, 0, 10, 11, 13,
	14, 15, 16, 0, 0, 0, 0, 0, 0, 9,
	0, 0, 0, 8,
}
var yyPact = [...]int{

	-1000, 89, -1000, 58, 19, -1000, -1000, -1000, 7, 7,
	21, -18, -1000, 7, 7, 7, 7, 7, 7, 7,
	7, 7, 7, -1000, 41, -1000, 17, 7, -14, -14,
	-1000, -1000, 80, 80, 80, 80, 80, 80, -1000, 7,
	23, 70, -21, 89, -24, 89, -4, -1000, -22, 89,
	-25, -1000,
}
var yyPgo = [...]int{

	0, 1, 30, 0, 41, 33, 29,
}
var yyR1 = [...]int{

	0, 6, 6, 2, 2, 2, 1, 1, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 4, 5, 5,
}
var yyR2 = [...]int{

	0, 0, 2, 2, 2, 1, 2, 1, 1, 1,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 2, 4, 7, 11,
}
var yyChk = [...]int{

	-1000, -6, -2, -3, -4, -5, 4, 5, 24, 20,
	8, 9, 6, 19, 20, 21, 22, 11, 12, 13,
	14, 15, 16, 6, -3, -3, 5, 24, -3, -3,
	-3, -3, -3, -3, -3, -3, -3, -3, 25, 7,
	-3, -3, 25, 26, -1, -2, 27, -1, 17, 26,
	-1, 27,
}
var yyDef = [...]int{

	1, -2, 2, 0, 0, 5, 8, 9, 0, 0,
	0, 0, 3, 0, 0, 0, 0, 0, 0, 0,
	0, 0, 0, 4, 0, 21, 0, 0, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 19, 20, 0,
	0, 22, 0, 0, 0, 7, 23, 6, 0, 0,
	0, 24,
}
var yyTok1 = [...]int{

	1, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	24, 25, 21, 19, 3, 20, 3, 22, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 3, 3, 3, 3, 3, 3, 3,
	3, 3, 3, 26, 3, 27,
}
var yyTok2 = [...]int{

	2, 3, 4, 5, 6, 7, 8, 9, 10, 11,
	12, 13, 14, 15, 16, 17, 18, 23,
}
var yyTok3 = [...]int{
	0,
}

var yyErrorMessages = [...]struct {
	state int
	token int
	msg   string
}{}

//line yaccpar:1

/*	parser for yacc output	*/

var (
	yyDebug        = 0
	yyErrorVerbose = false
)

type yyLexer interface {
	Lex(lval *yySymType) int
	Error(s string)
}

type yyParser interface {
	Parse(yyLexer) int
	Lookahead() int
}

type yyParserImpl struct {
	lval  yySymType
	stack [yyInitialStackSize]yySymType
	char  int
}

func (p *yyParserImpl) Lookahead() int {
	return p.char
}

func yyNewParser() yyParser {
	return &yyParserImpl{}
}

const yyFlag = -1000

func yyTokname(c int) string {
	if c >= 1 && c-1 < len(yyToknames) {
		if yyToknames[c-1] != "" {
			return yyToknames[c-1]
		}
	}
	return __yyfmt__.Sprintf("tok-%v", c)
}

func yyStatname(s int) string {
	if s >= 0 && s < len(yyStatenames) {
		if yyStatenames[s] != "" {
			return yyStatenames[s]
		}
	}
	return __yyfmt__.Sprintf("state-%v", s)
}

func yyErrorMessage(state, lookAhead int) string {
	const TOKSTART = 4

	if !yyErrorVerbose {
		return "syntax error"
	}

	for _, e := range yyErrorMessages {
		if e.state == state && e.token == lookAhead {
			return "syntax error: " + e.msg
		}
	}

	res := "syntax error: unexpected " + yyTokname(lookAhead)

	// To match Bison, suggest at most four expected tokens.
	expected := make([]int, 0, 4)

	// Look for shiftable tokens.
	base := yyPact[state]
	for tok := TOKSTART; tok-1 < len(yyToknames); tok++ {
		if n := base + tok; n >= 0 && n < yyLast && yyChk[yyAct[n]] == tok {
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}
	}

	if yyDef[state] == -2 {
		i := 0
		for yyExca[i] != -1 || yyExca[i+1] != state {
			i += 2
		}

		// Look for tokens that we accept or reduce.
		for i += 2; yyExca[i] >= 0; i += 2 {
			tok := yyExca[i]
			if tok < TOKSTART || yyExca[i+1] == 0 {
				continue
			}
			if len(expected) == cap(expected) {
				return res
			}
			expected = append(expected, tok)
		}

		// If the default action is to accept or reduce, give up.
		if yyExca[i+1] != 0 {
			return res
		}
	}

	for i, tok := range expected {
		if i == 0 {
			res += ", expecting "
		} else {
			res += " or "
		}
		res += yyTokname(tok)
	}
	return res
}

func yylex1(lex yyLexer, lval *yySymType) (char, token int) {
	token = 0
	char = lex.Lex(lval)
	if char <= 0 {
		token = yyTok1[0]
		goto out
	}
	if char < len(yyTok1) {
		token = yyTok1[char]
		goto out
	}
	if char >= yyPrivate {
		if char < yyPrivate+len(yyTok2) {
			token = yyTok2[char-yyPrivate]
			goto out
		}
	}
	for i := 0; i < len(yyTok3); i += 2 {
		token = yyTok3[i+0]
		if token == char {
			token = yyTok3[i+1]
			goto out
		}
	}

out:
	if token == 0 {
		token = yyTok2[1] /* unknown char */
	}
	if yyDebug >= 3 {
		__yyfmt__.Printf("lex %s(%d)\n", yyTokname(token), uint(char))
	}
	return char, token
}

func yyParse(yylex yyLexer) int {
	return yyNewParser().Parse(yylex)
}

func (yyrcvr *yyParserImpl) Parse(yylex yyLexer) int {
	var yyn int
	var yyVAL yySymType
	var yyDollar []yySymType
	_ = yyDollar // silence set and not used
	yyS := yyrcvr.stack[:]

	Nerrs := 0   /* number of errors */
	Errflag := 0 /* error recovery flag */
	yystate := 0
	yyrcvr.char = -1
	yytoken := -1 // yyrcvr.char translated into internal numbering
	defer func() {
		// Make sure we report no lookahead when not parsing.
		yystate = -1
		yyrcvr.char = -1
		yytoken = -1
	}()
	yyp := -1
	goto yystack

ret0:
	return 0

ret1:
	return 1

yystack:
	/* put a state and value onto the stack */
	if yyDebug >= 4 {
		__yyfmt__.Printf("char %v in %v\n", yyTokname(yytoken), yyStatname(yystate))
	}

	yyp++
	if yyp >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyS[yyp] = yyVAL
	yyS[yyp].yys = yystate

yynewstate:
	yyn = yyPact[yystate]
	if yyn <= yyFlag {
		goto yydefault /* simple state */
	}
	if yyrcvr.char < 0 {
		yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
	}
	yyn += yytoken
	if yyn < 0 || yyn >= yyLast {
		goto yydefault
	}
	yyn = yyAct[yyn]
	if yyChk[yyn] == yytoken { /* valid shift */
		yyrcvr.char = -1
		yytoken = -1
		yyVAL = yyrcvr.lval
		yystate = yyn
		if Errflag > 0 {
			Errflag--
		}
		goto yystack
	}

yydefault:
	/* default state action */
	yyn = yyDef[yystate]
	if yyn == -2 {
		if yyrcvr.char < 0 {
			yyrcvr.char, yytoken = yylex1(yylex, &yyrcvr.lval)
		}

		/* look through exception table */
		xi := 0
		for {
			if yyExca[xi+0] == -1 && yyExca[xi+1] == yystate {
				break
			}
			xi += 2
		}
		for xi += 2; ; xi += 2 {
			yyn = yyExca[xi+0]
			if yyn < 0 || yyn == yytoken {
				break
			}
		}
		yyn = yyExca[xi+1]
		if yyn < 0 {
			goto ret0
		}
	}
	if yyn == 0 {
		/* error ... attempt to resume parsing */
		switch Errflag {
		case 0: /* brand new error */
			yylex.Error(yyErrorMessage(yystate, yytoken))
			Nerrs++
			if yyDebug >= 1 {
				__yyfmt__.Printf("%s", yyStatname(yystate))
				__yyfmt__.Printf(" saw %s\n", yyTokname(yytoken))
			}
			fallthrough

		case 1, 2: /* incompletely recovered error ... try again */
			Errflag = 3

			/* find a state where "error" is a legal shift action */
			for yyp >= 0 {
				yyn = yyPact[yyS[yyp].yys] + yyErrCode
				if yyn >= 0 && yyn < yyLast {
					yystate = yyAct[yyn] /* simulate a shift of "error" */
					if yyChk[yystate] == yyErrCode {
						goto yystack
					}
				}

				/* the current p has no shift on "error", pop stack */
				if yyDebug >= 2 {
					__yyfmt__.Printf("error recovery pops state %d\n", yyS[yyp].yys)
				}
				yyp--
			}
			/* there is no state on the stack with an error shift ... abort */
			goto ret1

		case 3: /* no shift yet; clobber input char */
			if yyDebug >= 2 {
				__yyfmt__.Printf("error recovery discards %s\n", yyTokname(yytoken))
			}
			if yytoken == yyEofCode {
				goto ret1
			}
			yyrcvr.char = -1
			yytoken = -1
			goto yynewstate /* try again in the same state */
		}
	}

	/* reduction by production yyn */
	if yyDebug >= 2 {
		__yyfmt__.Printf("reduce %v in:\n\t%v\n", yyn, yyStatname(yystate))
	}

	yynt := yyn
	yypt := yyp
	_ = yypt // guard against "declared and not used"

	yyp -= yyR2[yyn]
	// yyp is now the index of $0. Perform the default action. Iff the
	// reduced production is ε, $1 is possibly out of range.
	if yyp+1 >= len(yyS) {
		nyys := make([]yySymType, len(yyS)*2)
		copy(nyys, yyS)
		yyS = nyys
	}
	yyVAL = yyS[yyp+1]

	/* consult goto table to find next state */
	yyn = yyR1[yyn]
	yyg := yyPgo[yyn]
	yyj := yyg + yyS[yyp].yys + 1

	if yyj >= yyLast {
		yystate = yyAct[yyg]
	} else {
		yystate = yyAct[yyj]
		if yyChk[yystate] != -yyn {
			yystate = yyAct[yyg]
		}
	}
	// dummy call; replaced with literal code
	switch yynt {

	case 2:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/grammar.y:33
		{
			fmt.Println(yylex.(*Lexer).eval(yyDollar[2].Ast))
		}
	case 8:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/grammar.y:48
		{
			yyVAL.Ast = &number{yyDollar[1].String}
		}
	case 9:
		yyDollar = yyS[yypt-1 : yypt+1]
//line cmd/grammar.y:49
		{
			yyVAL.Ast = &variable{yyDollar[1].String}
		}
	case 10:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/grammar.y:50
		{
			yyVAL.Ast = &binaryExpr{Op: "+", lhs: yyDollar[1].Ast, rhs: yyDollar[3].Ast}
		}
	case 11:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/grammar.y:51
		{
			yyVAL.Ast = &binaryExpr{Op: "-", lhs: yyDollar[1].Ast, rhs: yyDollar[3].Ast}
		}
	case 12:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/grammar.y:52
		{
			yyVAL.Ast = &binaryExpr{Op: "*", lhs: yyDollar[1].Ast, rhs: yyDollar[3].Ast}
		}
	case 13:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/grammar.y:53
		{
			yyVAL.Ast = &binaryExpr{Op: "/", lhs: yyDollar[1].Ast, rhs: yyDollar[3].Ast}
		}
	case 14:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/grammar.y:54
		{
			yyVAL.Ast = &binaryExpr{Op: yyDollar[2].String, lhs: yyDollar[1].Ast, rhs: yyDollar[3].Ast}
		}
	case 15:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/grammar.y:55
		{
			yyVAL.Ast = &binaryExpr{Op: yyDollar[2].String, lhs: yyDollar[1].Ast, rhs: yyDollar[3].Ast}
		}
	case 16:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/grammar.y:56
		{
			yyVAL.Ast = &binaryExpr{Op: yyDollar[2].String, lhs: yyDollar[1].Ast, rhs: yyDollar[3].Ast}
		}
	case 17:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/grammar.y:57
		{
			yyVAL.Ast = &binaryExpr{Op: yyDollar[2].String, lhs: yyDollar[1].Ast, rhs: yyDollar[3].Ast}
		}
	case 18:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/grammar.y:58
		{
			yyVAL.Ast = &binaryExpr{Op: yyDollar[2].String, lhs: yyDollar[1].Ast, rhs: yyDollar[3].Ast}
		}
	case 19:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/grammar.y:59
		{
			yyVAL.Ast = &binaryExpr{Op: yyDollar[2].String, lhs: yyDollar[1].Ast, rhs: yyDollar[3].Ast}
		}
	case 20:
		yyDollar = yyS[yypt-3 : yypt+1]
//line cmd/grammar.y:60
		{
			yyVAL.Ast = &parenExpr{yyDollar[2].Ast}
		}
	case 21:
		yyDollar = yyS[yypt-2 : yypt+1]
//line cmd/grammar.y:61
		{
			yyVAL.Ast = &unaryExpr{yyDollar[2].Ast}
		}
	case 22:
		yyDollar = yyS[yypt-4 : yypt+1]
//line cmd/grammar.y:65
		{
			yyVAL.Ast = &assignment{variable: yyDollar[2].String, expr: yyDollar[4].Ast}
		}
	case 23:
		yyDollar = yyS[yypt-7 : yypt+1]
//line cmd/grammar.y:69
		{
			yyVAL.Ast = &ifStatement{cond: yyDollar[3].Ast, thenStmt: yyDollar[6].Ast, elseStmt: nil}
		}
	case 24:
		yyDollar = yyS[yypt-11 : yypt+1]
//line cmd/grammar.y:70
		{
			yyVAL.Ast = &ifStatement{cond: yyDollar[3].Ast, thenStmt: yyDollar[6].Ast, elseStmt: yyDollar[10].Ast}
		}
	}
	goto yystack /* stack new state and value */
}
