name: "Go Setup"
description: "Setup Go"

inputs:
  github-token:
    description: "Github token"
    required: false
  go-version:
    description: "Go version"
    required: false
    default: "1.18"

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}

    - name: Set up gotestfmt
      uses: haveyoudebuggedit/gotestfmt-action@v2
      with:
        token: ${{ inputs.github-token }}
